version: '3.0'
services:
  rust:
    image: nomorechokedboy/web-project:seaorm-actix
    ports:
      - ${PORT}:${PORT}
    tty: true
    depends_on:
      - db
      - redis
    volumes:
      - ./data/rust:/data/rust
    env_file:
      - .env
    networks:
      - db-network
      - redis-network
    healthcheck:
      test:
        [
          'CMD',
          '/usr/bin/wget',
          '--no-verbose',
          '--tries=1',
          '--spider',
          'http://localhost:8000/getFuck/paging',
        ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    restart: always
