version: '3.8'
services:
  redis:
    container_name: redis
    image: redis:alpine
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - ./data/redis:/data
    user: '${UID_GID}'
    ports:
      - '6379:6379'
    networks:
      - redis-network
    restart: always
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  mysql:
    container_name: mysql
    image: mysql:5.7
    volumes:
      - ./data/mysql:/var/lib/mysql
    user: '${UID_GID}'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    networks:
      - db-network
    restart: always
    healthcheck:
      test: ['CMD', 'mysqladmin -uroot -ppassword', 'ping', '-h', 'localhost']
      timeout: 30s
      retries: 5
      start_period: 30s
      interval: 1m30s

networks:
  db-network:
    driver: bridge
  redis-network:
    driver: bridge
