version: '3.8'
services:
  redis:
    image: redis:alpine
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - ./data/redis:/data
    user: '${UID_GID}'
    ports:
      - '6379:6379'
    networks:
      - redis-network
    restart: always
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  db:
    image: postgres:14.1-alpine
    restart: always
    networks:
      - db-network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=actix_example
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready', '-d', 'db_prod']
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 30s

networks:
  db-network:
    driver: bridge
  redis-network:
    driver: bridge
