apiVersion: v1
kind: Service
metadata:
  name: actix-example
  # namespace: actix-example-local
spec:
  type: LoadBalancer
  selector:
    app: actix-example
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
